'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageThemes

    '''<summary>
    '''ucxThemeNavigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxThemeNavigation As Global.BetterclassifiedAdmin.LineAdThemeNavigation

    '''<summary>
    '''ucxMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxMessage As Global.BetterclassifiedAdmin.UserMessage

    '''<summary>
    '''btnCreateNewTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateNewTheme As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstThemes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstThemes As Global.System.Web.UI.WebControls.DataList
End Class
