'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _Default5

    '''<summary>
    '''ucxKeySearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxKeySearch As Global.BetterclassifiedsWeb.Controls.Search.KeySearch1

    '''<summary>
    '''LinkPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkPrint As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkOnline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkOnline As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Linkboth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Linkboth As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''categorySelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categorySelector As Global.BetterClassified.UI.CategorySelector

    '''<summary>
    '''ucxFlogSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxFlogSearch As Global.BetterclassifiedsWeb.FlogID

    '''<summary>
    '''lblSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchResults As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSearchResults As Global.BetterclassifiedsCore.UI.ParamountGrid

    '''<summary>
    '''objSourceResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objSourceResults As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
