'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DesignLineAd

    '''<summary>
    '''pnlBoldHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBoldHeading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HelpContextControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HelpContextControl1 As Global.Paramount.Common.UI.HelpContextControl

    '''<summary>
    '''btnUpgrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpgrade As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHeader As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHeadingLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeadingLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWordLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWordLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HelpContextControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HelpContextControl2 As Global.Paramount.Common.UI.HelpContextControl

    '''<summary>
    '''pnlWordsUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWordsUpdate As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnUpgradeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpgradeText As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lineAdDescriptionBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lineAdDescriptionBox As Global.BetterclassifiedsWeb.Controls.Booking.LineAdDescriptionBox

    '''<summary>
    '''btnPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreview As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnGetWords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetWords As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblWords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWords As Global.System.Web.UI.WebControls.Label
End Class
