'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Controls.Booking
    Partial Public Class Payment

        '''<summary>
        '''lblPaymentDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentDetails As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAmountLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAmountLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAmount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreditType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreditType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCreditCardType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCreditCardType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblCreditCardLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreditCardLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCreditCardNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreditCardNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valRequiredCC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRequiredCC As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblCardExpiryLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCardExpiryLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlMonthExpiry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMonthExpiry As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlYearExpiry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlYearExpiry As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblNameOnCardLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNameOnCardLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNameOnCard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNameOnCard As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''val control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents val As Global.System.Web.UI.WebControls.RequiredFieldValidator
    End Class
End Namespace