'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Register1

    '''<summary>
    '''SiteCreateUserWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiteCreateUserWizard As Global.System.Web.UI.WebControls.CreateUserWizard

    '''<summary>
    '''wizCreateUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizCreateUser As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''FirstNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstNameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFirstNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFirstNameTextBox As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''LastNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastNameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredLastNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredLastNameTextBox As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Address1TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address1TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredAddress1TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredAddress1TextBox As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CityTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CityTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredCityTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredCityTextBox As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''StateDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StateDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldState As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ZipCodeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ZipCodeTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''postCodeFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postCodeFilter As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''RequiredZipCodeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredZipCodeTextBox As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PhoneNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhoneNumberTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Filteredtextboxextender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''RequiredPhoneNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredPhoneNumberTextBox As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SecondaryPhoneTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondaryPhoneTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Filteredtextboxextender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''BusinessNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BusinessNameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ABNTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ABNTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Filteredtextboxextender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender3 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''pnlBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBusiness As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlIndustry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIndustry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlBusinesscategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBusinesscategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CreateUserWizardStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateUserWizardStep1 As Global.System.Web.UI.WebControls.CreateUserWizardStep

    '''<summary>
    '''CompleteWizardStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompleteWizardStep1 As Global.System.Web.UI.WebControls.CompleteWizardStep
End Class
