#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paramount.Betterclassifieds.DataService.Search
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iFlog")]
	public partial class ClassifiedsSearchEntitiesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ClassifiedsSearchEntitiesDataContext() : 
				base(global::Paramount.Betterclassifieds.DataService.Properties.Settings.Default.iFlogConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClassifiedsSearchEntitiesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClassifiedsSearchEntitiesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClassifiedsSearchEntitiesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClassifiedsSearchEntitiesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BookedAd> BookedAds
		{
			get
			{
				return this.GetTable<BookedAd>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BookedAd_GetById")]
		public ISingleResult<BookedAd> BookedAd_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> adId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adId);
			return ((ISingleResult<BookedAd>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BookedAd_Search")]
		public ISingleResult<BookedAd> BookedAd_Search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string searchTerm, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string categoryIds, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string locationIds, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string areaIds, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> order, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchTerm, categoryIds, locationIds, areaIds, order, pageIndex, pageSize);
			return ((ISingleResult<BookedAd>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BookedAds")]
	public partial class BookedAd
	{
		
		private int _OnlineAdId;
		
		private System.Nullable<int> _AdDesignId;
		
		private string _Heading;
		
		private string _Description;
		
		private string _HtmlText;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<int> _LocationId;
		
		private System.Nullable<int> _LocationAreaId;
		
		private string _ContactName;
		
		private string _ContactPhone;
		
		private string _ContactEmail;
		
		private System.Nullable<int> _NumOfViews;
		
		private string _OnlineAdTag;
		
		private int _AdId;
		
		private System.Nullable<System.DateTime> _BookingDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _UserId;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private string _CategoryName;
		
		private System.Nullable<int> _CategoryId;
		
		private System.Nullable<int> _ParentCategoryId;
		
		private string _LocationName;
		
		private string _LocationAreaName;
		
		private string _DocumentIds;
		
		private string _Publications;
		
		private int _TotalCount;
		
		private string _ParentCategoryName;
		
		private string _CategoryAdType;
		
		public BookedAd()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnlineAdId", DbType="Int NOT NULL")]
		public int OnlineAdId
		{
			get
			{
				return this._OnlineAdId;
			}
			set
			{
				if ((this._OnlineAdId != value))
				{
					this._OnlineAdId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdDesignId", DbType="Int")]
		public System.Nullable<int> AdDesignId
		{
			get
			{
				return this._AdDesignId;
			}
			set
			{
				if ((this._AdDesignId != value))
				{
					this._AdDesignId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heading", DbType="NVarChar(255)")]
		public string Heading
		{
			get
			{
				return this._Heading;
			}
			set
			{
				if ((this._Heading != value))
				{
					this._Heading = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HtmlText", DbType="NVarChar(MAX)")]
		public string HtmlText
		{
			get
			{
				return this._HtmlText;
			}
			set
			{
				if ((this._HtmlText != value))
				{
					this._HtmlText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationId", DbType="Int")]
		public System.Nullable<int> LocationId
		{
			get
			{
				return this._LocationId;
			}
			set
			{
				if ((this._LocationId != value))
				{
					this._LocationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationAreaId", DbType="Int")]
		public System.Nullable<int> LocationAreaId
		{
			get
			{
				return this._LocationAreaId;
			}
			set
			{
				if ((this._LocationAreaId != value))
				{
					this._LocationAreaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(200)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPhone", DbType="NVarChar(50)")]
		public string ContactPhone
		{
			get
			{
				return this._ContactPhone;
			}
			set
			{
				if ((this._ContactPhone != value))
				{
					this._ContactPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(100)")]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this._ContactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOfViews", DbType="Int")]
		public System.Nullable<int> NumOfViews
		{
			get
			{
				return this._NumOfViews;
			}
			set
			{
				if ((this._NumOfViews != value))
				{
					this._NumOfViews = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnlineAdTag", DbType="VarChar(50)")]
		public string OnlineAdTag
		{
			get
			{
				return this._OnlineAdTag;
			}
			set
			{
				if ((this._OnlineAdTag != value))
				{
					this._OnlineAdTag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", DbType="Int NOT NULL")]
		public int AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					this._AdId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BookingDate
		{
			get
			{
				return this._BookingDate;
			}
			set
			{
				if ((this._BookingDate != value))
				{
					this._BookingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(50)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="Int")]
		public System.Nullable<int> CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCategoryId", DbType="Int")]
		public System.Nullable<int> ParentCategoryId
		{
			get
			{
				return this._ParentCategoryId;
			}
			set
			{
				if ((this._ParentCategoryId != value))
				{
					this._ParentCategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationName", DbType="NVarChar(50)")]
		public string LocationName
		{
			get
			{
				return this._LocationName;
			}
			set
			{
				if ((this._LocationName != value))
				{
					this._LocationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationAreaName", DbType="NVarChar(50)")]
		public string LocationAreaName
		{
			get
			{
				return this._LocationAreaName;
			}
			set
			{
				if ((this._LocationAreaName != value))
				{
					this._LocationAreaName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentIds", CanBeNull=false)]
		public string DocumentIds
		{
			get
			{
				return this._DocumentIds;
			}
			set
			{
				if ((this._DocumentIds != value))
				{
					this._DocumentIds = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publications", CanBeNull=false)]
		public string Publications
		{
			get
			{
				return this._Publications;
			}
			set
			{
				if ((this._Publications != value))
				{
					this._Publications = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCount")]
		public int TotalCount
		{
			get
			{
				return this._TotalCount;
			}
			set
			{
				if ((this._TotalCount != value))
				{
					this._TotalCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCategoryName", CanBeNull=false)]
		public string ParentCategoryName
		{
			get
			{
				return this._ParentCategoryName;
			}
			set
			{
				if ((this._ParentCategoryName != value))
				{
					this._ParentCategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryAdType", CanBeNull=false)]
		public string CategoryAdType
		{
			get
			{
				return this._CategoryAdType;
			}
			set
			{
				if ((this._CategoryAdType != value))
				{
					this._CategoryAdType = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
