'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Step3

    '''<summary>
    '''ucxPageErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxPageErrors As Global.BetterclassifiedsWeb.ErrorList

    '''<summary>
    '''helpContextPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helpContextPanel As Global.Paramount.Common.UI.HelpContextControl

    '''<summary>
    '''lblInfoImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoImages As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkUploadImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkUploadImages As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''radWindowImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radWindowImages As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''ucxLineAdDesign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxLineAdDesign As Global.BetterclassifiedsWeb.DesignLineAd

    '''<summary>
    '''ucxDesignOnlineAd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxDesignOnlineAd As Global.BetterclassifiedsWeb.DesignOnlineAd

    '''<summary>
    '''ucxNavButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxNavButtons As Global.BetterclassifiedsWeb.NavigationButtons
End Class
