
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

GO
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'ClusteredIndex-OnlineAdId' AND object_id = OBJECT_ID('OnlineAdView'))
begin
	CREATE UNIQUE CLUSTERED INDEX [ClusteredIndex-OnlineAdId] ON [dbo].[OnlineAdView]
	(
		[OnlineAdId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
end

GO
