'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports BetterclassifiedsCore
Imports BetterclassifiedsCore.CRM


Namespace AdminDataService

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AdminDataService.IDataService")> _
    Public Interface IDataService

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataService/GetCustomerList", ReplyAction:="http://tempuri.org/IDataService/GetCustomerListResponse")> _
        Function GetCustomerList() As BetterclassifiedsCore.CRM.Customer()

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataService/GetCustomer", ReplyAction:="http://tempuri.org/IDataService/GetCustomerResponse")> _
        Function GetCustomer(ByVal username As String) As Customer

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataService/GetCustomerListByUsername", ReplyAction:="http://tempuri.org/IDataService/GetCustomerListByUsernameResponse")> _
        Function GetCustomerListByUsername(ByVal username As String) As Customer()

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataService/GetCustomerListByCompany", ReplyAction:="http://tempuri.org/IDataService/GetCustomerListByCompanyResponse")> _
        Function GetCustomerListByCompany(ByVal company As String) As Customer()

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataService/GetCustomerListByLastname", ReplyAction:="http://tempuri.org/IDataService/GetCustomerListByLastnameResponse")> _
        Function GetCustomerListByLastname(ByVal lastName As String) As Customer()

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataService/GetCustomerListByPhone", ReplyAction:="http://tempuri.org/IDataService/GetCustomerListByPhoneResponse")> _
        Function GetCustomerListByPhone(ByVal phone As String) As Customer()

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDataService/UpdateCustomer", ReplyAction:="http://tempuri.org/IDataService/UpdateCustomerResponse")> _
        Function UpdateCustomer(ByVal customer As Customer) As Boolean
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Public Interface IDataServiceChannel
        Inherits AdminDataService.IDataService, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Partial Public Class DataServiceClient
        Inherits System.ServiceModel.ClientBase(Of AdminDataService.IDataService)
        Implements AdminDataService.IDataService

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        Public Function GetCustomerList() As Customer() Implements AdminDataService.IDataService.GetCustomerList
            Return MyBase.Channel.GetCustomerList
        End Function

        Public Function GetCustomer(ByVal username As String) As Customer Implements AdminDataService.IDataService.GetCustomer
            Return MyBase.Channel.GetCustomer(username)
        End Function

        Public Function GetCustomerListByUsername(ByVal username As String) As Customer() Implements AdminDataService.IDataService.GetCustomerListByUsername
            Return MyBase.Channel.GetCustomerListByUsername(username)
        End Function

        Public Function GetCustomerListByCompany(ByVal company As String) As Customer() Implements AdminDataService.IDataService.GetCustomerListByCompany
            Return MyBase.Channel.GetCustomerListByCompany(company)
        End Function

        Public Function GetCustomerListByLastname(ByVal lastName As String) As Customer() Implements AdminDataService.IDataService.GetCustomerListByLastname
            Return MyBase.Channel.GetCustomerListByLastname(lastName)
        End Function

        Public Function GetCustomerListByPhone(ByVal phone As String) As Customer() Implements AdminDataService.IDataService.GetCustomerListByPhone
            Return MyBase.Channel.GetCustomerListByPhone(phone)
        End Function

        Public Function UpdateCustomer(ByVal customer As Customer) As Boolean Implements AdminDataService.IDataService.UpdateCustomer
            Return MyBase.Channel.UpdateCustomer(customer)
        End Function
    End Class
End Namespace
