'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default4

    '''<summary>
    '''categorySelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categorySelector As Global.BetterClassified.UI.CategorySelector

    '''<summary>
    '''ucxFlogSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxFlogSearch As Global.BetterclassifiedsWeb.FlogID

    '''<summary>
    '''ucxRecentlyAdded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucxRecentlyAdded As Global.BetterclassifiedsWeb.Controls.Search.RecentOnlineAdList
End Class
