<?xml version="1.0" encoding="utf-8"?><Database Name="ParamountCore" Class="BannerDatabaseModelDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=paramountit.com.au;Initial Catalog=ParamountCore;Integrated Security=True;Persist Security Info=True" SettingsObjectName="Paramount.Betterclassifieds.DataService.Properties.Settings" SettingsPropertyName="ParamountCoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BannerReference" Member="BannerReferences">
    <Type Name="BannerReference">
      <Column Name="BannerReferenceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BannerReferenceTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BannerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="BannerReferenceType_BannerReference" Member="BannerReferenceType" ThisKey="BannerReferenceTypeId" OtherKey="BannerReferenceTypeId" Type="BannerReferenceType" IsForeignKey="true" />
      <Association Name="Banner_BannerReference" Member="Banner" ThisKey="BannerId" OtherKey="BannerId" Type="Banner" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BannerReferenceType" Member="BannerReferenceTypes">
    <Type Name="BannerReferenceType">
      <Column Name="BannerReferenceTypeId" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="BannerReferenceType_BannerReference" Member="BannerReferences" ThisKey="BannerReferenceTypeId" OtherKey="BannerReferenceTypeId" Type="BannerReference" />
    </Type>
  </Table>
  <Table Name="dbo.BannerFileType" Member="BannerFileTypes">
    <Type Name="BannerFileType">
      <Column Name="BannerFileTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="BannerFileType_BannerGroup" Member="BannerGroups" ThisKey="Code" OtherKey="AcceptedFileType" Type="BannerGroup" />
    </Type>
  </Table>
  <Table Name="dbo.BannerGroup" Member="BannerGroups">
    <Type Name="BannerGroup">
      <Column Name="BannerGroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AcceptedFileType" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="IsTimerEnabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="BannerGroup_Banner" Member="Banners" ThisKey="BannerGroupId" OtherKey="BannerGroupId" Type="Banner" />
      <Association Name="BannerFileType_BannerGroup" Member="BannerFileType" ThisKey="AcceptedFileType" OtherKey="Code" Type="BannerFileType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Banner" Member="Banners">
    <Type Name="Banner">
      <Column Name="BannerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BannerGroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DocumentID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NavigateUrl" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RequestCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClickCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Banner_BannerReference" Member="BannerReferences" ThisKey="BannerId" OtherKey="BannerId" Type="BannerReference" />
      <Association Name="Banner_BannerAudit" Member="BannerAudits" ThisKey="BannerId" OtherKey="BannerId" Type="BannerAudit" />
      <Association Name="BannerGroup_Banner" Member="BannerGroup" ThisKey="BannerGroupId" OtherKey="BannerGroupId" Type="BannerGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BannerAudit" Member="BannerAudits">
    <Type Name="BannerAudit">
      <Column Name="BannerAuditId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BannerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ActionTypeName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UserGroup" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Banner_BannerAudit" Member="Banner" ThisKey="BannerId" OtherKey="BannerId" Type="Banner" IsForeignKey="true" />
    </Type>
  </Table>
</Database>